### ISSUE TITLE
Proposal: Automatic recovery procedure

### ISSUE THREAD

**Issue by tamalsaha** [appscode/glusterfs#21]
@sadlil , Let's use this as an umbrella issue to capture all the things that glusterc does and does not do for automatic recovery.

- [ ] [Automagic unsplit-brain by [ctime|mtime|size|majority]](https://github.com/appscode/glusterfs/issues/8)
- [ ] [Configure alerts for GlusterFS](https://github.com/appscode/glusterfs/issues/11)

Use reset-brick command to replace bad disk(s) within a volume. http://blog.gluster.org/2016/11/announcing-gluster-3-9/ . I have added 3.9 docker images.

**Comment by TamalSaha** [comment]
I have added 3.9 docker images.
